# Generated by Django 5.2.6 on 2025-09-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=40, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=200, verbose_name='دامنه سایت')),
                ('site_logo', models.ImageField(upload_to='images/site_settings/', verbose_name='لوگو سایت')),
                ('addres', models.CharField(max_length=200, verbose_name='آدرس')),
                ('tell', models.CharField(max_length=20, verbose_name='تلفن')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('copy_right_text', models.CharField(max_length=400, verbose_name='متن کپی رایت')),
                ('about_us_page', models.CharField(verbose_name='درباره ما')),
                ('is_main_settings', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان لینک')),
                ('descriptuon', models.TextField(max_length=200, verbose_name='توضیحات اسلایدر')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='تصویر اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
