# Generated by Django 5.2.6 on 2025-09-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک'),
        ),
    ]
