# Generated by Django 5.2.6 on 2025-10-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_alter_slider_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات'},
        ),
    ]
